name: Generate appcast.xml

on:
  workflow_dispatch:

jobs:
  generate-appcast:
    name: Generate appcast.xml
    runs-on: ubuntu-latest
    environment: appcast
    steps:
      - uses: actions/checkout@v4

      - name: Generate appcast.xml
        run: |
          cd cmd/ghreleases2appcast
          go run . -o ../../appcast.xml

      - name: Push to object store
        uses: docker://docker.io/rclone/rclone:latest
        env:
          RCLONE_CONFIG_OBJSTORE_TYPE: ${{ secrets.AZUREBLOB_TYPE }}
          RCLONE_CONFIG_OBJSTORE_ACCOUNT: ${{ secrets.AZUREBLOB_ACCOUNT }}
          RCLONE_CONFIG_OBJSTORE_KEY: ${{ secrets.AZUREBLOB_KEY }}
        with:
          args: copy appcast.xml objstore:macos/appcast/
