name: Generate appcast.xml

on:
  workflow_dispatch:
  schedule:
    - cron: '42 3 * * *'

jobs:
  generate-appcast:
    name: Generate appcast.xml
    runs-on: ubuntu-latest
    environment: appcast
    steps:
      - uses: actions/checkout@v3

      - name: Generate appcast.xml
        run: |
          cd cmd/ghreleases2appcast
          go run . -o ../../appcast.xml

      - name: Push to object store
        uses: docker://docker.io/rclone/rclone:latest
        env:
          RCLONE_CONFIG_OBJSTORE_TYPE: s3
          RCLONE_CONFIG_OBJSTORE_PROVIDER: ${{ secrets.S3_PROVIDER }}
          RCLONE_CONFIG_OBJSTORE_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          RCLONE_CONFIG_OBJSTORE_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          RCLONE_CONFIG_OBJSTORE_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
          RCLONE_CONFIG_OBJSTORE_REGION: ${{ secrets.S3_REGION }}
          RCLONE_CONFIG_OBJSTORE_ACL: public-read
        with:
          args: copy appcast.xml objstore:syncthing-macos/appcast/
